server:
  port: 8000

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
      # defaultZone: http://127.0.0.1:8762/eureka, http://local.amadda.com:8763/eureka

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          [/**]:
            allowed-origins: "*"
            allowed-methods: "*"
            allowed-headers: "*"
            allow-credentials: true
            max-age: 3600
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/amadda