spring:
  application:
    name: account-service
eureka:
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
      # defaultZone: http://localhost:8762/eureka/, http://local.amadda.com:8763/eureka
keycloak:
  serverUrl:
  realm:
  clientId:
  clientSecret:
  username:
  password:
server:
  port: 0
